# .github/workflows/ci.yml
name: CI/CD for Python App

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-python-app .

      - name: Simulate deployment
        run: echo "Deployment to staging server successful (simulated)"

  notify:
    needs: docker-build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: CI/CD Pipeline Success
          to: farebl.04@gmail.com
          from: GitHub Actions <your-email@example.com>
          body: The CI/CD pipeline for my-python-project has completed successfully!
